title: Arden Stone
email: ardenstone@gmail.com
theme: jekyll-theme-tactile
twitter: https://twitter.com/ardenstone
github: [metadata]
number: (318) 995-4463
domain: arden.codes
linkedin: https://www.linkedin.com/in/arden-stone-bb1660130/